// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CargaVentas.Data.Context;
using CargaVentas.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace CargaVentas.Data.Context.Configurations
{
    public partial class CityConfiguration : IEntityTypeConfiguration<City>
    {
        public void Configure(EntityTypeBuilder<City> entity)
        {
            entity.HasKey(e => e.CityId).HasName("PK__Cities__F2D21A96F114CDD3");

            entity.Property(e => e.CityId)
                .ValueGeneratedNever()
                .HasColumnName("CityID");
            entity.Property(e => e.City1)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("City");
            entity.Property(e => e.Country)
                .HasMaxLength(100)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<City> entity);
    }
}
