// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CargaVentas.Data.Context;
using CargaVentas.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace CargaVentas.Data.Context.Configurations
{
    public partial class OrdersDetailConfiguration : IEntityTypeConfiguration<OrdersDetail>
    {
        public void Configure(EntityTypeBuilder<OrdersDetail> entity)
        {
            entity.HasKey(e => e.OrderDetailId).HasName("PK__OrdersDe__D3B9D30C99FC3C66");

            entity.Property(e => e.OrderDetailId)
                .ValueGeneratedNever()
                .HasColumnName("OrderDetailID");
            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.ProductId).HasColumnName("ProductID");
            entity.Property(e => e.TotalPrice).HasColumnType("decimal(10, 2)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OrdersDetail> entity);
    }
}
