// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CargaVentas.Data.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public decimal? Price { get; set; }

    public int? CategoryId { get; set; }

    public int? Stock { get; set; }
}